//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Oesia.Repository {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Oesia.Repository.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spr_deleteAuthor {0}.
        /// </summary>
        internal static string SpDeleteAuthor {
            get {
                return ResourceManager.GetString("SpDeleteAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spr_deleteBook {0}.
        /// </summary>
        internal static string SpDeleteBook {
            get {
                return ResourceManager.GetString("SpDeleteBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EXEC spr_getAllAuthor.
        /// </summary>
        internal static string SpGetAllAuthors {
            get {
                return ResourceManager.GetString("SpGetAllAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spr_getAllBook.
        /// </summary>
        internal static string SpGetAllBooks {
            get {
                return ResourceManager.GetString("SpGetAllBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spr_getAllCity.
        /// </summary>
        internal static string SpGetAllCities {
            get {
                return ResourceManager.GetString("SpGetAllCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spr_getAllCountry.
        /// </summary>
        internal static string SpGetAllCountries {
            get {
                return ResourceManager.GetString("SpGetAllCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spr_getAllEditorial.
        /// </summary>
        internal static string SpGetAllEditorials {
            get {
                return ResourceManager.GetString("SpGetAllEditorials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spr_getAllGender.
        /// </summary>
        internal static string SpGetAllGenders {
            get {
                return ResourceManager.GetString("SpGetAllGenders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spr_getAllState.
        /// </summary>
        internal static string SpGetAllStates {
            get {
                return ResourceManager.GetString("SpGetAllStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spr_getByIdAuthor {0}.
        /// </summary>
        internal static string SpGetByIdAuthor {
            get {
                return ResourceManager.GetString("SpGetByIdAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spr_getByIdBook {0}.
        /// </summary>
        internal static string SpGetByIdBook {
            get {
                return ResourceManager.GetString("SpGetByIdBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spr_insertAuthor {0},{1},{2},{3},{4},{5},{6},{7},{8}.
        /// </summary>
        internal static string SpInsertAuthor {
            get {
                return ResourceManager.GetString("SpInsertAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spr_insertBook {0},{1},{2},{3},{4},{5},{6}.
        /// </summary>
        internal static string SpInsertBook {
            get {
                return ResourceManager.GetString("SpInsertBook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spr_updateAuthor {0},{1},{2},{3},{4},{5},{6},{7},{8},{9}.
        /// </summary>
        internal static string SpUpdateAuthor {
            get {
                return ResourceManager.GetString("SpUpdateAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a spr_updateBook {0},{1},{2},{3},{4},{5},{6},{7}.
        /// </summary>
        internal static string SpUpdateBook {
            get {
                return ResourceManager.GetString("SpUpdateBook", resourceCulture);
            }
        }
    }
}
